# Generated by Django 4.1.3 on 2023-01-06 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_bookinstance_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='loved_books',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='username',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
