# Generated by Django 4.1.3 on 2023-01-06 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_book_user_loved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user_loved',
        ),
        migrations.AddField(
            model_name='book',
            name='user_loved',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
