# Generated by Django 4.1.3 on 2023-01-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_delete_post_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.FileField(upload_to='books/')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
