# Generated by Django 4.1.3 on 2023-01-20 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_post_remove_book_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.FileField(default=django.utils.timezone.now, upload_to='books/'),
            preserve_default=False,
        ),
    ]
